README.md
Instructions are outdated and make building fail.
=> Update repository name in README.

postgresql/provider.go
The docs have long since been updated to use the `sslmode` spelling.
=> Mark `ssl_mode` as the deprecated spelling of `sslmode`.

postgresql/config.go
Fixes https://github.com/terraform-providers/terraform-provider-postgresql/issues/30
=> Use ParseTolerant to allow Major.Minor version numbers that PG 10 uses

CHANGELOG.md, postgresql/resource_postgresql_role.go, postgresql/resource_postgresql_role_test.go, website/docs/r/postgresql_role.html.markdown
This PR depends on the work of @nguse in #44 which is fixing diff for encrypted password.
Our enhancements:
* Really updating password in the `resourcePostgreSQLRoleUpdate` function.
* Don't compare password if the role has not `login` access. Otherwise there's no entry in `pg_shadow`  for it  and plan will always want to update it. (This fixes the tests)
* Force to set the password if the role is renamed. As the [documentation](https://www.postgresql.org/docs/current/sql-alterrole.html) says:
> Because MD5-encrypted passwords use the role name as cryptographic salt, renaming a role clears its password if the password is MD5-encrypted.
Fix #16
=> Fix role password

.travis.yml, CHANGELOG.md, postgresql/config.go, postgresql/resource_postgresql_database.go, postgresql/resource_postgresql_database_test.go, postgresql/resource_postgresql_extension.go, postgresql/resource_postgresql_extension_test.go, postgresql/resource_postgresql_role.go, tests/docker-compose.yml, tests/env.sh, tests/wait-postgres-docker.sh
Acceptance tests was not run in Travis so I configured Travis to start Postgres server in a Docker container (with a Matrix of versions from 8.4 to latest) and enable acceptance tests against it.
By running these tests, I discovered multiple bugs that I fixed:
* The version features flags system was not working because the detected version was not correctly set in the Client struct...
* Database update was not working because of invalid SQL queries (using of statement parameters syntax "$1" but not for parameters...)
* Disable postgresql_extension resource (and associated tests) for Postgres < 9.1 (`CREATE EXTENSION` does not exists before this version)
* Add a replication flag (available for >=9.1)
fix #35
=> Travis: Build agains multiple Postgres version + fix bugs

CHANGELOG.md, postgresql/config.go, postgresql/provider.go, postgresql/resource_postgresql_database.go, postgresql/resource_postgresql_role.go, website/docs/index.html.markdown
With [user name maps](https://www.postgresql.org/docs/current/auth-username-maps.html), connection username can be different than associated role name in database.
Fix #55
=> config: Add a database_username parameter for users map.

CHANGELOG.md, postgresql/helpers.go, postgresql/resource_postgresql_database.go, postgresql/resource_postgresql_database_test.go, postgresql/utils_test.go
The owner was revoked from connected user even in the case where the grant was not needed because the it was already a member of the owner role.
Depends on #58 
(I move the grant/revoke methods in `helpers.go` because we'll need to do the same things in `postgresql_role` for the `REASSIGN OWNER` , see #36 )
=> Fix the way the owner is granted / revoked when managing a database.

postgresql/provider_test.go
This should prevent crashes when running tests, e.g.
```
Test ended in panic.
------- Stdout: -------
=== RUN   TestAccPostgresqlDatabase_Update
--- FAIL: TestAccPostgresqlDatabase_Update (0.00s)
------- Stderr: -------
panic: interface conversion: interface {} is nil, not *postgresql.Client [recovered]
panic: interface conversion: interface {} is nil, not *postgresql.Client
goroutine 20 [running]:
testing.tRunner.func1(0xc00011e300)
/opt/goenv/versions/1.11.5/src/testing/testing.go:792 +0x387
panic(0xcaf5c0, 0xc000231050)
/opt/goenv/versions/1.11.5/src/runtime/panic.go:513 +0x1b9
github.com/terraform-providers/terraform-provider-postgresql/postgresql.TestAccPostgresqlDatabase_Update.func1()
/opt/teamcity-agent/work/476074bb45c53ed2/src/github.com/terraform-providers/terraform-provider-pos …
```
=> tests: Configure provider before running test

CHANGELOG.md, postgresql/config.go, postgresql/provider.go, postgresql/resource_postgresql_role.go, postgresql/resource_postgresql_role_test.go
Before version 0.2.0,  password update was not correctly updated. Now that it has been fixed (see #54), this breaks `postgresql_role` resource when admin user configured in provider is not a SUPERUSER (permission denied on pg_shadow when trying to refresh password in state). 
Which is the case with RDS for example.
This PR adds a way to specify that admin user is not superuser so password will not be refresh in state.
Password update still works as long as all modifications are done with Terraform (so if passwords are not manually updated in database).
Fix #64 
Configuration example:
```
provider "postgresql" {
host = "localhost"
port = "5432"
username  = "postgres"
password  = "xxx"
superuser = false
}
resource "postgresql_role" "test" {
name     = "test"
login    = true
password = …
```
=> postgresql_role: Don't refresh password from Postgres if not superuser

website/docs/index.html.markdown
This was added in 0.2.1 via #66 but undocumented.
=> Add documentation for `superuser` provider setting

CHANGELOG.md, postgresql/config.go, postgresql/helpers.go, postgresql/provider.go, postgresql/resource_postgresql_database.go, postgresql/resource_postgresql_database_test.go, postgresql/resource_postgresql_default_privileges.go, postgresql/resource_postgresql_default_privileges_test.go, postgresql/resource_postgresql_extension_test.go, postgresql/resource_postgresql_grant.go, postgresql/resource_postgresql_grant_test.go, postgresql/resource_postgresql_role.go, postgresql/resource_postgresql_role_test.go, postgresql/resource_postgresql_schema.go, postgresql/utils_test.go, vendor/github.com/hashicorp/terraform/helper/structure/expand_json.go, vendor/github.com/hashicorp/terraform/helper/structure/flatten_json.go, vendor/github.com/hashicorp/terraform/helper/structure/normalize_json.go, vendor/github.com/hashicorp/terraform/helper/structure/suppress_json_diff.go, vendor/github.com/hashicorp/terraform/helper/validation/validation.go, website/docs/r/postgresql_default_privileges.html.markdown, website/docs/r/postgresql_grant.html.markdown, website/postgresql.erb
Add resources:
* postgresql_grant: Allow to manage [grant](https://www.postgresql.org/docs/current/sql-grant.html)  for tables or sequences for a specified role in a schema.
* postgresql_default_privileges: Allow to manage [default privileges](https://www.postgresql.org/docs/current/sql-alterdefaultprivileges.html) for tables or sequences for a specified role in a schema.
=> New resources: postgresql_grant & postgresql_default_privileges

postgresql/resource_postgresql_role.go, postgresql/resource_postgresql_role_test.go
The timestamp must be enclosed with ` not ".
I attempted to modify the test case, but its tricky with timestamps and I couldn't get past the apply error which always showed a diff on the valid_until due to timestamp formatting issues.
=> Use literal quotes with VALID UNTIL

postgresql/resource_postgresql_default_privileges_test.go, postgresql/resource_postgresql_grant.go, postgresql/resource_postgresql_grant_test.go, postgresql/utils_test.go
To check if `postgresql_grant` or `postgresql_default_privileges` resources exist,
the provider is first checking if database/schema for which they will be applied exist.
For the schema, we created a specific connection on the right database to check
it but it was mistakenly using the wrong connection and was checking if schema exists
on the database defined in provider.
(Basically it was working only for schema `public` which exists by default in all databases)
@multani This is the bug we talked about. Could you have a look please?
=> grant/default privileges: Fix schema verification.

CHANGELOG.md, postgresql/resource_postgresql_role.go, postgresql/resource_postgresql_role_test.go, website/docs/r/postgresql_role.html.markdown
This allows to grant roles to the role we are managing.
Example:
```hcl
resource postgresql_role "test_group" {
name = "test_group"
}
resource postgresql_role "test_role" {
name  = "test_role"
roles = ["${postgresql_role.test_group.name}"]
}
```
Fix #21 
This probably conflicts with #23
=> postgresql_role: Add roles attribute.

postgresql/resource_postgresql_extension.go
The CREATE EXTENSION command will fail if the extension exists. IF NOT EXISTS ignores the error.
=> Add IF NOT EXISTS to CREATE EXTENSION

CHANGELOG.md, postgresql/resource_postgresql_role.go, postgresql/resource_postgresql_role_test.go, website/docs/r/postgresql_role.html.markdown
This PR adds a new attribute to `postgresql_role` that allows one to set the search path of the new role. Let me know if there's anything I missed or can improve!
=> postgresql_role: add optional attribute to set search_path

postgresql/helpers.go, postgresql/resource_postgresql_schema.go, postgresql/resource_postgresql_schema_test.go
Hello,
For now `postgresql_schema` resource use database parameter set in provider definition. If database do not exist (ex: the first time) postgresql provider fail.
In other postgresql resources we need to pass database parameter at resource level.
This change add database parameter on `resource_postgresql_schema`.
=> resource_postgresql_schema: Add database optional parameter

postgresql/config.go, postgresql/provider.go
Fixes #2, perhaps controversially.
The reason it's not currently possible to provision, e.g., an RDS instance and modify it with a `postgresql_*` resource is that the `postgresql` provider attempts to parse the PostgreSQL version by connecting to the database during the planning phase.
This pull request allows the user to prevent this from happening by specifying the version directly via the existing `expected_version` parameter. In practice, you would do something like:
```hcl
resource "aws_db_instance" "this" {
[...]
}
provider "postgresql" {
[...]
expected_version = aws_db_instance.this.engine_version
}
```
The behavior of the provider if `expected_version` is not supplied remains the same.
=> Trust `expected_version` if provided

CHANGELOG.md, postgresql/resource_postgresql_schema.go, postgresql/resource_postgresql_schema_test.go, website/docs/r/postgresql_schema.html.markdown
This allows to delete cascade all dependent objects while deleting a schema.
fix #101
=> postgresql_schema: Add drop_cascade option.

postgresql/helpers.go, postgresql/resource_postgresql_role.go, postgresql/resource_postgresql_role_test.go
set `statement_timeout` to role
> statement_timeout (integer)
Abort any statement that takes more than the specified number of milliseconds, starting from the time the command arrives at the server from the client.
=> [add] set statement_timeout to role

go.mod, go.sum
A simple PR to upgrade the Go lib/pq to v1.3.0.
This allow to use SCRAM-SHA-256 encrypted password for provider authentication.
=> Upgrade lib/pq to v1.3.0

README.md
Update the "use" section to link to the official provider usage documentation, instead of a placeholder TODO
=> Update README with link to Terraform doc

website/docs/r/postgresql_schema.html.markdown
Hey there!
The current documentation for `postgres_schema` doesn't reference how to change the database that the schema is in. I assumed that it would use the `provider` configuration to infer this but really it just defaults to `postgres` and it can be overridden via configuration so I just added some documentation for this feature.
Cheers
=> Add missing documentation specifying the database for `postgresql_schema`

postgresql/helpers.go, postgresql/resource_postgresql_database.go, postgresql/resource_postgresql_role.go, postgresql/resource_postgresql_schema.go
The plugin SDK provides helper validation functions that are well tested and used in a lot of places.
In general we should prefer to use these where possible instead of rolling our own functions that do the same thing.
I noticed this after the recent release and looking at https://github.com/terraform-providers/terraform-provider-postgresql/pull/105 but only after it had been merged.
Output from `terraform validate` after this change:
```
Error: expected connection_limit to be at least (-1), got -2
on main.tf line 1, in resource "postgresql_role" "my_role":
1: resource "postgresql_role" "my_role" {
Error: expected statement_timeout to be at least (0), got -1
on main.tf line 1, in resource "postgresql_role" "my_role":
1: resource "postgresql_role" "my_role" {
```
which is arguably slightly …
=> Replace unnecessary validation functions with validators from the plugin SDK

postgresql/config.go, postgresql/provider.go, website/docs/index.html.markdown
Fixes: #49 
Adds a new optional nested block to the provider configuration for SSL client certificate files paths.
Example:
```hcl
provider "postgresql" {
host = "localhost"
clientcert {
cert     = "client-cert.pem"
key      = "client-key.pem"
}
sslrootcert = "server-ca.pem"
}
```
I tried to match the coding conventions of the project as best as I understand them.  I'm happy to adjust the property names if there are preferences from reviewers.
=> Provider Configuration: Support SSL Client Certificates

postgresql/provider.go
fix #125 
It should allow to set 0 which means unlimited.
I also increase the default value up to 20.
4 is quite low (especially when using database specific resources).
This also uses Terraform helpers for int validation instead of custom functions.
=> Fix max_connections validations.

postgresql/helpers.go, postgresql/resource_postgresql_default_privileges.go, postgresql/resource_postgresql_grant.go, postgresql/resource_postgresql_grant_test.go, postgresql/utils_test.go
I'm following @tgermain's [comment](https://github.com/terraform-providers/terraform-provider-postgresql/issues/85#issuecomment-581424768) (we work together) regarding the proposal to handle `GRANT` on databases (in addition to sequences and tables).
I took the liberty to move the query string creation (for both grant and revoke queries) into two dedicated functions and write unit test for them (although I'm a test newbie). Feel free to discard that if you find it irrelevant.
=> Implement grants on database

CHANGELOG.md, postgresql/helpers.go, postgresql/resource_postgresql_default_privileges.go, postgresql/resource_postgresql_grant.go, postgresql/resource_postgresql_grant_test.go, website/docs/r/postgresql_default_privileges.html.markdown, website/docs/r/postgresql_grant.html.markdown
This extends both, postgresql_grant and postgresql_default_privileges to grant execute on functions in addition to the existing table and sequence object types. Test are updated as well documentations
=> add feature grant functions

postgresql/helpers.go, postgresql/resource_postgresql_default_privileges.go, postgresql/resource_postgresql_grant.go, website/docs/r/postgresql_default_privileges.html.markdown
As asked in this [issue](https://github.com/terraform-providers/terraform-provider-postgresql/issues/95), I wanted to add support for functions and types for default privileges.
By the way, those two new objects types also suffers from this [issue](https://github.com/terraform-providers/terraform-provider-postgresql/issues/72)
I did not know how to test it, I can update the PR if anyone has ideas to improve the PR.
=> [resource_postgresql_default_privileges] add support for types default privileges

postgresql/helpers.go, postgresql/provider.go, postgresql/resource_postgresql_database.go, postgresql/resource_postgresql_database_test.go, postgresql/resource_postgresql_default_privileges.go, postgresql/resource_postgresql_extension_test.go, postgresql/resource_postgresql_grant.go, postgresql/resource_postgresql_role.go, postgresql/resource_postgresql_role_test.go, postgresql/resource_postgresql_schema.go, postgresql/resource_postgresql_schema_test.go, postgresql/utils_test.go, tests/env.sh, tests/switch_rds.sh, tests/switch_superuser.sh, tests/testacc_cleanup.sh, tests/testacc_full.sh, tests/testacc_setup.sh, tests/wait-postgres-docker.sh
This should fix most of permissions problems the provider has when running against RDS databases (and maybe other Cloud provider, but didn't test yet)
This also adds a new run of integration tests against a RDS-like Postgres.
Some tests are disabled for this environment, either because it really need to be superuser (e.g. to create a new superuser) or because the environment is not totally similar as RDS (e.g.: for the extensions, I need to check how I can reproduce RDS behavior).
This replaces #139 and #135 
Thanks to @slocke716 and @rimmington for your work on these problems that help me to create a more generic fix. If you have time to test this PR on your environment to assert it fixes your use cases, and even more to make a review of this PR, it would be very helpful :blush: .
This …
=> all resources: Grant object owners to connected user when needed.

postgresql/resource_postgresql_role.go
This PR fixes resource attribute key for bypass RLS flag on reading `role` resource.
In the current implementation, bypass RLS flag value will be set to `replication` resource attribute key.
However, I think bypass RLS flag value should be set to `bypass_row_level_security` resource attribute key.
So, this PR fixes resource attribute key.
=> Fix resource attribute key for bypass RLS flag

postgresql/resource_postgresql_extension.go, postgresql/resource_postgresql_extension_test.go
This allows to drop the extension even if it has dependencies.
Fix: #137
For the test: ideally there's a test where there's a dependency and `drop_cascade = false` and it shows it's failing. I'm not sure how to write that though.
=> Support DROP EXTENSION xx CASCADE

CHANGELOG.md, postgresql/resource_postgresql_grant.go
This small fixes addresses issue #159  regarding grant on functions in versions before PGSQL11. I think its save to remove selection of column `prokind` (f=normal functions, a=aggregate function and w=window function)  from pgproc dataset as its not to expect to have the same name in more than one kind
=> remove prokind selection as is not available before PGSQL 11, fix #159
